# Generated by Django 4.0.8 on 2024-08-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_transport_engine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='car_picture',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
