# Generated by Django 4.0.8 on 2024-08-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_transport_car_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='car_picture',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
